services:
  catalogdb:
    image: postgres

  catalog.api:
    image: arigatory/catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
volumes:
  postgres_catalog: